### ISSUE TITLE
Rimuovere la time signature negli esempi lilypond

### ISSUE THREAD

**Issue by nicb** [nicb/dispense#10]
In molti esempi `lilypond` la time signature e' completamente inutile anzi dannosa. Giuse', come si fa a rimuoverla? Se mi dici fasso mi, altrimenti ti fa ti e poi committi.

**Comment by nicb** [comment]
Vorrei rimuovere anche il numero di battuta, che anch'esso non ha veramente nessun senso.

**Comment by grammaton** [comment]
Ok Lo fo in giornata. Fico! Il mio primo assignment

**Comment by grammaton** [comment]
ho rimosso la time signature dove mi sembrava superflua e i numeri battuta ovunque. committo. andrebbe aperta una nuova issue per sistemare gli esempi e scriverli tutti allo stesso modo, alcuni possono essere scritti un po' meglio e si potrebbe omologare ancora di più il setup. facciamo però un'altra issue ;)
