### ISSUE TITLE
make dist : failed on a mac

### ISSUE THREAD

**Issue by grammaton** [nicb/dispense#17]
> $ make dist
make: Entering directory `/Users/giuseppe/Git_REPO/_NICB/dispense/slides/TCMC'
idirs=`echo ../argomenti/storia/immagini | sed 's/:/ /'g`;\
		for i in $idirs;\
		do\
				/Applications/Xcode.app/Contents/Developer/usr/bin/make -C $i -w;\
		done
make[1]: Entering directory `/Users/giuseppe/Git_REPO/_NICB/dispense/slides/argomenti/storia/immagini'
lilypond --pdf -dno-gs-load-fonts -dinclude-eps-fonts chrom-mediants-maj.ly
GNU LilyPond 2.18.2
Processing `chrom-mediants-maj.ly'
Parsing...
Interpreting music...
Preprocessing graphical objects...Fontconfig warning: ignoring UTF-8: not a valid region tag
dyld: lazy symbol binding failed: Symbol not found: __ZNSt8__detail15_List_node_base7_M_hookEPS0_
  Referenced from: /usr/local/bin/lilypond
  Expected in: /usr/lib/libstdc++.6.dylib
>
> dyld: Symbol not found: __ZNSt8__detail15_List_node_base7_M_hookEPS0_
  Referenced from: /usr/local/bin/lilypond
  Expected in: /usr/lib/libstdc++.6.dylib
>
> make[1]: *** [chrom-mediants-maj.pdf] Trace/BPT trap: 5
make[1]: Leaving directory `/Users/giuseppe/Git_REPO/_NICB/dispense/slides/argomenti/storia/immagini'
make: *** [images] Error 2
make: Leaving directory `/Users/giuseppe/Git_REPO/_NICB/dispense/slides/TCMC'
$

**Comment by nicb** [comment]
Questo sembra essere un errore con l'installazione di `lilypond`. Ossia: &egrave; `lilypond` che va a sbattere, non `make`.
